title: Wang KaiLong「王凯龙」
# title: Wang KaiLong
name: "Wang KaiLong"
author: Wang KaiLong
twitter_username: Wang KaiLong
baseurl: ""
description: Document my learning notes.
# profile_url: "https://sunchangsheng.com"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3
